# ~/.bashrc.d/bash_aliases

# Option presets

# bat
function bman {
    man $1 | bat -l man --style=plain --theme TwoDark
}
alias bcat='bat --theme TwoDark --style=plain --paging=never'
alias bnum='bat --theme TwoDark --style=plain --number'
alias bless='bat --theme TwoDark --style=plain'

# ps
alias psc='ps xawf -eo pid,user,cgroup,args'

# rsync
alias rget='rsync -r -v --progress -c --partial -e ssh'

# zellij
alias zel='zellij --layout compact options --simplified-ui true --theme catppuccin-mocha'

# mpv/mplayer
# alias mpa='mplayer -vo null'
# alias mpp='mplayer -ao null -fs'
alias mpa='mpv --no-video'
alias mpp='mpv --fs --no-audio'

# Handle typos
alias :q='exit'
alias :Q='exit'
alias lcd='cd'
alias lls='ls'

# Ping
alias ping-1='ping 1.1.1.1'
alias ping-8='ping 8.8.8.8'
