import = ["~/.config/alacritty/tokyo-night.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13.0

[font.bold]
family = "Fira Code"
style = "SemiBold,Regular"

[font.normal]
family = "Fira Code"
style = "Retina,Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
opacity = 0.95
startup_mode = "Windowed"

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 10
y = 15
